# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField()),
                ('drop_off_time', models.TimeField()),
                ('pick_up_time', models.TimeField()),
                ('event_date', models.DateField()),
                ('event_name', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('forward_payment', models.FloatField()),
                ('tax_percentage', models.FloatField()),
                ('delivery_cost', models.FloatField()),
                ('state', models.PositiveSmallIntegerField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Client')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Location')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.FloatField()),
                ('comments', models.TextField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Item')),
            ],
        ),
    ]
