# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170601_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='delivery_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='forward_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tax_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
