# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-02 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20170702_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='billing_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
