# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20170703_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='billing_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
